### ISSUE TITLE
#목표 2 [진우]

### ISSUE THREAD

**Issue by ymw0407** [WebOS-KOSS/entrance_cam#3]
지금까지 녹화하고, 녹화한 영상을 구글 드라이브에 올리는 과정을 구현해내었다.
이번의 목표는 @bentshrimp 와 함께 녹화가 시작되는 조건, 마무리하고 구글 드라이브에 올라가게 되는 조건을 넣어주는 것이 될 것이다.

**Comment by bentshrimp** [comment]
아니 왜 설치 안되는건데 import error만 뒤지게 많이 뜸 죽고 싶다

**Comment by bentshrimp** [comment]
녹화까지 성공
